export const chatgptPlans = [
  {
    slug: "plus-shared",
    title: "ChatGPT Plus — Shared Seat",
    plan: "Plus",
    tier: "Shared",
    priceBDT: 399,
    priceLabel: "৳399/month",
    seats: 8,
    duration: "30 days",
    deliverySLA: "5–15 minutes",
    accessType: "shared",
    deviceRule: "1 device only",
    warranty: "Full for 30 days. Void on misuse/ban/password change/multi-device.",
    segment: "Budget",
    targetBuyer: "Students, beginners",
    badge: "Most Popular",
    color: "blue"
  },
  {
    slug: "plus-premium-shared",
    title: "ChatGPT Plus — Premium Shared",
    plan: "Plus",
    tier: "Premium Shared",
    priceBDT: 950,
    priceLabel: "৳950/month",
    seats: "2–3",
    duration: "30 days",
    deliverySLA: "5–15 minutes",
    accessType: "shared",
    deviceRule: "1 device only",
    warranty: "Full for subscription period. Void on misuse/ban.",
    segment: "Quality",
    targetBuyer: "Freelancers, creators",
    badge: "Stable",
    color: "purple"
  },
  {
    slug: "plus-personal-seat",
    title: "ChatGPT Plus — Personal Seat",
    plan: "Plus",
    tier: "Personal Seat",
    priceBDT: 2950,
    priceLabel: "৳2,950/month",
    seats: 1,
    duration: "30 days",
    deliverySLA: "5–15 minutes",
    accessType: "customer-owned",
    deviceRule: "No restriction (your account)",
    warranty: "Tied to your own account management.",
    segment: "Professional",
    targetBuyer: "Power users",
    badge: "Own Account",
    color: "green"
  },
  {
    slug: "business-shared",
    title: "ChatGPT Business — Shared",
    plan: "Business",
    tier: "Shared",
    priceBDT: 699,
    priceLabel: "৳699/month",
    seats: 7,
    duration: "30 days",
    deliverySLA: "Up to 12 hours",
    accessType: "workspace-invite",
    deviceRule: "Workspace rules apply",
    warranty: "Subject to Business workspace rules.",
    segment: "Team Budget",
    targetBuyer: "Small teams",
    badge: "Team",
    color: "orange"
  },
  {
    slug: "business-premium-shared",
    title: "ChatGPT Business — Premium Shared",
    plan: "Business",
    tier: "Premium Shared",
    priceBDT: 1299,
    priceLabel: "৳1,299/month",
    seats: "2–3",
    duration: "30 days",
    deliverySLA: "Up to 12 hours",
    accessType: "workspace-invite",
    deviceRule: "Workspace rules apply",
    warranty: "Subject to Business workspace rules.",
    segment: "Team Quality",
    targetBuyer: "Agencies",
    badge: "Stable Team",
    color: "orange"
  },
  {
    slug: "business-personal-like",
    title: "ChatGPT Business — Personal-like",
    plan: "Business",
    tier: "Personal-like",
    priceBDT: 3899,
    priceLabel: "৳3,899/month",
    seats: 1,
    duration: "30 days",
    deliverySLA: "Up to 12 hours",
    accessType: "workspace-invite",
    deviceRule: "Dedicated experience",
    warranty: "Subject to Business workspace rules.",
    segment: "Team Pro",
    targetBuyer: "Businesses, agencies",
    badge: "Dedicated",
    color: "orange"
  },
  {
    slug: "pro-premium-shared",
    title: "ChatGPT Pro — Premium Shared",
    plan: "Pro",
    tier: "Premium Shared",
    priceBDT: 4500,
    priceLabel: "৳4,500/month",
    seats: "5–6",
    duration: "30 days",
    deliverySLA: "5–15 minutes",
    accessType: "shared",
    deviceRule: "1 device only",
    warranty: "Full for subscription period. Void on misuse/ban.",
    segment: "Pro",
    targetBuyer: "Heavy power users",
    badge: "Most Powerful",
    color: "red"
  }
];
